apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base/cert-manager
- ../../base/pad
- ../../base/prometheus
- ../../base/vault
patchesJson6902:
- target:
    group: apps
    version: v1
    kind: Deployment
    name: cryptpad
  path: pad.yaml
