apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base/cert-manager
- ../../base/grafana
- ../../base/pad
- ../../base/prometheus
patchesStrategicMerge:
- pad-patch.yaml
