---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base/cert-manager
- ../../base/cryptpad
- ../../base/dendrite
- ../../base/external-dns
- ../../base/grafana
- ../../base/prometheus
- ../../base/snowflake
