---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cryptpad
  namespace: cryptpad
spec:
  template:
    spec:
      containers:
        - name: cryptpad
          image: quay.io/ffddorf/cryptpad:4.12.0 # {"$imagepolicy": "cryptpad:cryptpad"}
