apiVersion: apps/v1
kind: Deployment
metadata:
  name: cryptpad
  namespace: cryptpad
spec:
  template:
    spec:
      containers:
      - name: cryptpad
        image: quay.io/ffddorf/cryptpad:5.2.1 # {"$imagepolicy": "cryptpad:cryptpad"}
