---
apiVersion: v1
kind: Namespace
metadata:
  name: metallb-system
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: metallb
spec:
  url: https://metallb.github.io/metallb
  interval: 1h
---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: metallb
spec:
  interval: 24h
  install:
    createNamespace: false
  chart:
    spec:
      chart: metallb
      version: "0.x"
      sourceRef:
        kind: HelmRepository
        name: metallb
