apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: dendrite
  namespace: dendrite
spec:
  values:
    dendrite_config:
      global:
        server_name: freifunk-duesseldorf.de
        well_known_server_name: dendrite.ffddorf.net
        well_known_client_name: dendrite.ffddorf.net
    ingress:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
      hostName: dendrite.ffddorf.net
      tls: 
      - hosts: [ dendrite.ffddorf.net ]
        secretName: dendrite-tls

