apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../environments/prod
images:
- name: quay.io/ffddorf/cryptpad
  newName: quay.io/ffddorf/cryptpad # {"$imagepolicy": "cryptpad:cryptpad:name"}
  newTag: 4.12.0 # {"$imagepolicy": "cryptpad:cryptpad:tag"}
