---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- flux-system
- ../../environments/prod
- traefik-config.yaml
- apps.yaml
patchesStrategicMerge:
- dendrite-helm-release.yaml
- grafana-helm-release.yaml
