apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cryptpad
  namespace: cryptpad
spec:
  commonName: pad.freifunk-duesseldorf.de
  secretName: cryptpad-tls-prod
  dnsNames:
    - pad.freifunk-duesseldorf.de
    - cryptpad.freifunk-duesseldorf.de
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
