---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: cryptpad
  namespace: cryptpad
spec:
  imageRepositoryRef:
    name: cryptpad
  policy:
    semver:
      range: '>=1.0.0'
