{
 "title": "Jitsi Meet Stats",
 "description": "Statistics of our Jitsi Meet video conference servers",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "jvb", "label": "Videobridge", "query": "SHOW MEASUREMENTS" }
  ]
 },
 "panels": [
  {
   "title": "number of current conferences",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "limit": "1",
     "measurement": "/^$jvb$/",
     "query": "SELECT last(\"conferences\") FROM /^$/ WHERE  GROUP BY time(10s) fill(previous)",
     "select": [
      [
       { "params": [ "conferences" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "total of current participants",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "limit": "1",
     "measurement": "/^$jvb$/",
     "query": "SELECT sum(\"participants\") FROM \"exec_meet\" WHERE (\"host\" =~ /^$/) AND  GROUP BY time() fill(previous)",
     "select": [
      [
       { "params": [ "participants" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "largest conference participants",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "limit": "1",
     "measurement": "/^$jvb$/",
     "query": "SELECT sum(\"participants\") FROM \"exec_meet\" WHERE (\"host\" =~ /^$/) AND  GROUP BY time() fill(previous)",
     "select": [
      [
       { "params": [ "largest_conference" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "traffic volume per hour",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "/^$jvb$/",
     "query": "SELECT mean(\"bytes_sent\") FROM \"net\" WHERE (\"host\" = 'select tag value') AND  GROUP BY time() fill(null)",
     "select": [
      [
       {
        "params": [
         "node_network_transmit_bytes_total"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "sum"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "current data rate incoming",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "/^$jvb$/",
     "query": "SELECT non_negative_derivative(sum(\"bytes_recv\"), 1s) *8 FROM \"net\" WHERE (\"host\" =~ /^jvb[0-9]+.meet.ffmuc.net/ AND \"interface\" = 'eth0' OR \"host\" =~ /^jvb[0-9]+.meet.ffmuc.net/ AND \"interface\" =~ /ens/) AND  GROUP BY time() fill(linear)",
     "select": [
      [
       {
        "params": [
         "node_network_receive_bytes_total"
        ],
        "type": "field"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "*8" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "current data rate outgoing",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "/^$jvb$/",
     "query": "SELECT non_negative_derivative(sum(\"bytes_sent\"), 1s) *8 FROM \"net\" WHERE (\"host\" =~ /^jvb[0-9]+.meet.ffmuc.net/ AND \"interface\" = 'eth0' OR \"host\" =~ /^jvb[0-9]+.meet.ffmuc.net/ AND \"interface\" =~ /ens/) AND  GROUP BY time() fill(linear)",
     "select": [
      [
       {
        "params": [
         "node_network_transmit_bytes_total"
        ],
        "type": "field"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "*8" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "number of conferences",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "/^$jvb$/",
     "query": "SELECT mean(\"conferences\") FROM \"exec_meet\" WHERE  GROUP BY time(), \"host\" fill(null)",
     "select": [
      [
       { "params": [ "conferences" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "number of participants",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "/^$jvb$/",
     "query": "SELECT mean(\"participants\") FROM \"exec_meet\" WHERE  GROUP BY time(), \"host\" fill(null)",
     "select": [
      [
       { "params": [ "participants" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "number of streams",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": ":  Running",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "/^$jvb$/",
     "select": [
      [
       { "params": [ "videostreams" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "median latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "/^$jvb$/",
     "query": "SELECT mean(\"average_response_ms\") FROM \"ping\" WHERE (\"url\" =~ /jvb/) AND  GROUP BY time(), \"url\" fill(null)",
     "select": [
      [
       { "params": [ "rtt_aggregate" ], "type": "field" },
       {
        "params": [],
        "type": "median"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "data rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "alias": " RX",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "/^$jvb$/",
     "query": "SELECT non_negative_derivative(mean(\"bytes_recv\"), 1s) *8 FROM \"net\" WHERE (\"host\" =~ /^$/ AND  \"host\" =~ /^jvb[0-9]+.meet.ffmuc.net$/ ) AND  GROUP BY time(), \"host\" fill(null)",
     "select": [
      [
       {
        "params": [
         "node_network_receive_bytes_total"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "*8" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": " TX",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "/^$jvb$/",
     "query": "SELECT non_negative_derivative(mean(\"bytes_sent\"), 1s) *8 FROM \"net\" WHERE (\"host\" =~ /^$/ AND  \"host\" =~ /^jvb[0-9]+.meet.ffmuc.net$/ ) AND  GROUP BY time(), \"host\" fill(null)",
     "select": [
      [
       {
        "params": [
         "node_network_transmit_bytes_total"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "*8" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "daily max. number of conferences",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "1d" ], "type": "time" }
     ],
     "measurement": "/^$jvb$/",
     "query": "SELECT mean(\"conferences\") FROM \"exec_meet\" WHERE  GROUP BY time(), \"host\" fill(null)",
     "select": [
      [
       { "params": [ "conferences" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "daily max. number of participants",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "1d" ], "type": "time" }
     ],
     "measurement": "/^$jvb$/",
     "query": "SELECT mean(\"conferences\") FROM \"exec_meet\" WHERE  GROUP BY time(), \"host\" fill(null)",
     "select": [
      [
       { "params": [ "participants" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    }
   ]
  }
 ]
}