---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: jitsi
resources:
- namespace.yaml
- service-chaosdorf.yaml
- service-ffddorf.yaml
- service-monitor.yaml
configMapGenerator:
- name: grafana-dashboard
  files:
  - grafana-dashboard.json
generatorOptions:
  disableNameSuffixHash: true
  labels:
    grafana_dashboard: "true"
