---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: jitsi
resources:
- grafana-datasource.yaml
- namespace.yaml
configMapGenerator:
- name: grafana-dashboard
  files:
  - grafana-dashboard.json
generatorOptions:
  disableNameSuffixHash: true
  labels:
    grafana_dashboard: "true"
