---
apiVersion: v1
kind: Service
metadata:
  name: jitsi-service-ffddorf
  labels:
    name: jitsi
spec:
  type: ExternalName
  externalName: jitsi.freifunk-duesseldorf.de
  ports:
  - name: metrics
    port: 8080
    protocol: TCP
    targetPort: metrics
---
apiVersion: v1
kind: Endpoints
metadata:
  name: jitsi-service-ffddorf
  labels:
    name: jitsi
subsets:
  - addresses:
    - ip: 45.151.166.22
    ports:
      - name: metrics
        port: 9080
        protocol: TCP
