---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-dns
spec:
  chart:
    spec:
      chart: external-dns
      sourceRef:
        kind: HelmRepository
        name: external-dns
  interval: 1h
  releaseName: external-dns
  values:
    provider: cloudflare
    domainFilters:
    - ffddorf.net
    env:
    - name: CF_API_TOKEN
      valueFrom:
        secretKeyRef:
          name: cloudflare-secret
          key: token
    - name: CF_API_EMAIL
      valueFrom:
        secretKeyRef:
          name: cloudflare-secret
          key: email
