apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: grafana
  namespace: grafana
spec:
  interval: 10m
  path: "base/grafana"
  sourceRef:
    kind: GitRepository
    name: fleet-infra
