apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: grafana
spec:
  interval: 1h
  install:
    createNamespace: false
  chart:
    spec:
      chart: grafana
      sourceRef:
        kind: HelmRepository
        name: grafana
  values:
    serviceMonitor:
      enabled: true
    grafana.ini:
      auth.anonymous:
        enabled: true
        org_name: Main Org.
        org_role: Viewer
      auth:
        disable_login_form: true
      users:
        default_theme: system
    sidecar:
      dashboards:
        enabled: true
        provider:
          disableDelete: true
        reloadURL: "http://grafana/api/admin/provisioning/dashboards/reload"
        searchNamespace: ALL
      datasources:
        enabled: true
        searchNamespace: ALL
        reloadURL: "http://grafana/api/admin/provisioning/datasources/reload"
    persistence:
      inMemory:
        enabled: true
    serviceAccount:
      autoMount: true
