---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: grafana
spec:
  interval: 1h
  install:
    createNamespace: false
  chart:
    spec:
      chart: grafana
      sourceRef:
        kind: HelmRepository
        name: grafana
  values:
    serviceMonitor:
      enabled: true
    grafana.ini:
      auth.anonymous:
        enabled: true
        org_name: Main Org.
        org_role: Viewer
      auth:
        disable_login_form: true
      server:
        root_url: https://grafana.ffddorf.net
      server.custom_response_headers:
        Access-Control-Allow-Origin: https://chaosdorf.de
      users:
        auto_assign_org_role: Admin
        default_theme: system
      auth.github:
        enabled: true
        auto_login: true
        allowed_organizations: ffddorf
        skip_org_role_sync: true
        client_id: $__file{/secrets/grafana-secret/client_id}
        client_secret: $__file{/secrets/grafana-secret/client_secret}
    extraSecretMounts:
      - name: grafana-secret
        secretName: grafana-secret
        defaultMode: 0440
        mountPath: /secrets/grafana-secret
        readOnly: true
    sidecar:
      dashboards:
        enabled: true
        provider:
          disableDelete: true
        reloadURL: "http://grafana/api/admin/provisioning/dashboards/reload"
        searchNamespace: ALL
      datasources:
        enabled: true
        searchNamespace: ALL
        reloadURL: "http://grafana/api/admin/provisioning/datasources/reload"
    persistence:
      inMemory:
        enabled: true
    serviceAccount:
      autoMount: true
