apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: grafana
spec:
  interval: 1h
  install:
    createNamespace: false
  chart:
    spec:
      chart: grafana
      sourceRef:
        kind: HelmRepository
        name: grafana
  values:
    serviceMonitor:
      enabled: true
    ingress:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
        traefik.ingress.kubernetes.io/router.entrypoints: websecure,web
        traefik.ingress.kubernetes.io/router.middlewares: jitsi-secured@kubernetescrd
        traefik.ingress.kubernetes.io/router.tls: "true"
      hosts:
      - grafana.jitsi.freifunk-duesseldorf.de
      tls:
      - secretName: grafana-tls
        hosts:
        - grafana.jitsi.freifunk-duesseldorf.de
    grafana.ini:
      auth.anonymous:
        enabled: true
        org_name: Main Org.
        org_role: Viewer
      auth:
        disable_login_form: true
    sidecar:
      dashboards:
        enabled: true
        provider:
          disableDelete: true
      datasources:
        enabled: true
        searchNamespace: ALL
