---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasource-prometheus
  labels:
    grafana_datasource: "1"
data:
  datasource.yaml: |-
    apiVersion: 1
    datasources:
    - access: proxy
      basicAuth: false
      editable: false
      isDefault: true
      name: Prometheus
      type: prometheus
      url: http://prometheus-kube-prometheus-prometheus.prometheus:9090
